[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Discrete Math"

[preprocessor.katex]
after = ["links"]

[build]
build-dir = "output"
create-missing = true
use-default-preprocessors = false
